package playground

object DependencyHolder {
    val text = """
        zebraPayment -> accountApi
        zebraPayment -> libCommon
        zebraPayment -> zebraRouter
        zebraPayment -> frog
        zebraPayment -> log
        zebraPayment -> forkMainLib
        zebraPayment -> zebraui
        zebraPayment -> commonData
        zebraPayment -> zebraShareApi
        zebraPayment -> zebraPaymentApi
        zebraPayment -> net
        bizPoetryRecite -> zebraRouter
        bizPoetryRecite -> commonUi
        bizPoetryRecite -> mediaplayerApi
        bizPoetryRecite -> log
        bizPoetryRecite -> zebraDownloaderApi
        bizPoetryRecite -> zebraPreDownloaderApi
        bizPoetryRecite -> storage
        bizPoetryRecite -> mediaplayerDumb
        bizPoetryRecite -> zebraShareDumb
        bizPoetryRecite -> libCommon
        bizPoetryRecite -> commonResources
        bizPoetryRecite -> frog
        bizPoetryRecite -> zebraShareApi
        bizPoetryRecite -> net
        bizPoetryRecite -> mvrx
        bizPoetryRecite -> forkMainResources
        bizPoetryRecite -> bizPoetryReciteApi
        bizPoetryRecite -> zebraRecognizeApi
        bizPoetryRecite -> forkMainLib
        bizPoetryRecite -> commonData
        bizPoetryRecite -> zebraLottie
        bizPoetryRecite -> accountApi
        bizPoetryRecite -> zebraMediaPlayerApi
        bizPoetryRecite -> zebraui
        zebraMemoryMonitorApi -> libCommon
        zebraMemoryMonitorApi -> libRouter
        zebraMemoryMonitorApi -> commonData
        zebraRouter -> log
        zebraRouter -> bizHomeSupportApi
        zebraRouter -> zebraPrivacyApi
        zebraRouter -> momentApi
        zebraRouter -> libCommon
        zebraRouter -> bizTvClassApi
        zebraRouter -> bizAccountApi
        zebraRouter -> frog
        zebraRouter -> zebraShareApi
        zebraRouter -> liveWrapperApi
        zebraRouter -> net
        zebraRouter -> zebraCocosApi
        zebraRouter -> appApi
        zebraRouter -> zebraConfigApi
        zebraRouter -> forkMainLib
        zebraRouter -> commonData
        zebraRouter -> servCommon
        zebraRouter -> bizPotterApi
        zebraRouter -> bizUnitReviewApi
        zebraRouter -> bizPicbookApi
        zebraRouter -> serverApi
        zebraRouter -> accountApi
        zebraRouter -> libRouter
        zebraRouter -> zebraCustomerServiceApi
        zebraRouter -> liveCommerceWrapperApi
        zebraRouter -> zebraui
        zebraRouter -> kiddoForAppApi
        zebraRouter -> bizHomeApi
        zebraRouter -> webAppApi
        zebraPreDownloaderApi -> libCommon
        zebraPreDownloaderApi -> libRouter
        zebraPreDownloaderApi -> commonData
        zebraMqttApi -> libCommon
        zebraMqttApi -> libRouter
        zebraMqttApi -> commonData
        bizHomeHDApi -> libCommon
        bizHomeHDApi -> libRouter
        bizHomeHDApi -> commonData
        bizHomeHDApi -> bizHomeApi
        bizEvaluate -> accountApi
        bizEvaluate -> libCommon
        bizEvaluate -> commonResources
        bizEvaluate -> commonUi
        bizEvaluate -> libRouter
        bizEvaluate -> forkMainResources
        bizEvaluate -> frog
        bizEvaluate -> commonData
        bizEvaluate -> bizEvaluateApi
        bizEvaluate -> net
        zebraUpgrade -> zebraUpgradeApi
        zebraUpgrade -> libCommon
        zebraUpgrade -> libRouter
        zebraUpgrade -> frog
        zebraUpgrade -> log
        zebraUpgrade -> forkMainLib
        zebraUpgrade -> zebraui
        zebraUpgrade -> commonData
        zebraUpgrade -> servCommon
        zebraUpgrade -> net
        zebraUpgrade -> zebraConfigApi
        bizAiTalkApi -> libCommon
        bizAiTalkApi -> libRouter
        bizAiTalkApi -> commonData
        zebraRecognize -> forkMainResources
        zebraRecognize -> zebraRecognizeApi
        zebraRecognize -> log
        zebraRecognize -> mediaplayerApi
        zebraRecognize -> forkMainLib
        zebraRecognize -> commonData
        zebraRecognize -> zebraDownloaderApi
        zebraRecognize -> zebraLottie
        zebraRecognize -> accountApi
        zebraRecognize -> libCommon
        zebraRecognize -> commonResources
        zebraRecognize -> zebraMediaPlayerApi
        zebraRecognize -> libRouter
        zebraRecognize -> frog
        zebraRecognize -> zebraui
        zebraRecognize -> net
        zebraRecognize -> zebraConfigApi
        zebraPrivacyApi -> libCommon
        zebraPrivacyApi -> libRouter
        zebraPrivacyApi -> commonData
        bizAccount -> zebraRouter
        bizAccount -> log
        bizAccount -> mediaplayerApi
        bizAccount -> forkMainLib
        bizAccount -> commonData
        bizAccount -> servCommon
        bizAccount -> bizPotterApi
        bizAccount -> storage
        bizAccount -> serverApi
        bizAccount -> zebraPrivacyApi
        bizAccount -> mediaplayerDumb
        bizAccount -> accountApi
        bizAccount -> libCommon
        bizAccount -> bizAccountApi
        bizAccount -> zebraMiscApi
        bizAccount -> frog
        bizAccount -> zebraui
        bizAccount -> net
        bizAccount -> mvrx
        bizAccount -> zebraUploaderApi
        bizAccount -> appApi
        zebraMiscApi -> libCommon
        zebraMiscApi -> libRouter
        zebraMiscApi -> commonData
        devtoolsApi -> libCommon
        devtoolsApi -> libRouter
        devtoolsApi -> commonData
        bizBaseSubjectApi -> libCommon
        bizBaseSubjectApi -> libRouter
        bizBaseSubjectApi -> commonData
        zebraCocos -> zebraRouter
        zebraCocos -> zebraRecognizeApi
        zebraCocos -> log
        zebraCocos -> forkMainLib
        zebraCocos -> commonData
        zebraCocos -> zebraDownloaderApi
        zebraCocos -> zebraPreDownloaderApi
        zebraCocos -> bizHomeSupportApi
        zebraCocos -> storage
        zebraCocos -> errorReportApi
        zebraCocos -> serverApi
        zebraCocos -> accountApi
        zebraCocos -> libCommon
        zebraCocos -> zebraMediaPlayerApi
        zebraCocos -> frog
        zebraCocos -> zebraui
        zebraCocos -> zebraShareApi
        zebraCocos -> net
        zebraCocos -> zebraCocosApi
        zebraCocos -> zebraConfigApi
        zebraCocos -> appApi
        zebraPreDownloader -> log
        zebraPreDownloader -> servCommon
        zebraPreDownloader -> zebraDownloaderApi
        zebraPreDownloader -> commonData
        zebraPreDownloader -> zebraPreDownloaderApi
        zebraPreDownloader -> storage
        zebraPreDownloader -> bizPicbookApi
        zebraPreDownloader -> libCommon
        zebraPreDownloader -> libRouter
        zebraPreDownloader -> bizBaseSubjectApi
        zebraPreDownloader -> liveWrapperApi
        zebraPreDownloader -> zebraDownloaderDumb
        zebraPreDownloader -> net
        zebraPreDownloader -> zebraConfigApi
        zebraPreDownloader -> appApi
        zebraPreDownloader -> bizHomeApi
        galleryApi -> libCommon
        galleryApi -> libRouter
        galleryApi -> commonData
        galleryApi -> legacyApiCall
        legacyApiCall -> httpStatusCode
        zebraMemoryMonitor -> libCommon
        zebraMemoryMonitor -> zebraMemoryMonitorApi
        zebraMemoryMonitor -> libRouter
        zebraMemoryMonitor -> log
        zebraMemoryMonitor -> commonData
        zebraMemoryMonitor -> net
        zebraMemoryMonitor -> zebraConfigApi
        zebraCocosApi -> libCommon
        zebraCocosApi -> libRouter
        zebraCocosApi -> commonData
        errorReport -> libCommon
        errorReport -> libRouter
        errorReport -> commonData
        errorReport -> errorReportApi
        errorReport -> zebraConfigApi
        gallery -> zebraShareDumb
        gallery -> libCommon
        gallery -> zebraRouter
        gallery -> log
        gallery -> forkMainLib
        gallery -> zebraui
        gallery -> commonData
        gallery -> zebraShareApi
        gallery -> galleryApi
        gallery -> storage
        gallery -> net
        bizSplash -> zebraRouter
        bizSplash -> log
        bizSplash -> forkMainLib
        bizSplash -> commonData
        bizSplash -> storage
        bizSplash -> errorReportApi
        bizSplash -> zebraPrivacyApi
        bizSplash -> bizSplashApi
        bizSplash -> accountApi
        bizSplash -> libCommon
        bizSplash -> libRouter
        bizSplash -> frog
        bizSplash -> zebraui
        bizSplash -> bizLaunchApi
        bizSplash -> net
        app -> zebraMediaPlayerDumb
        app -> zebraRouter
        app -> mediaplayerApi
        app -> webAppDumb
        app -> zebraPreDownloaderApi
        app -> bizBaseSubject
        app -> bizAiTalkApi
        app -> zebraPrivacyApi
        app -> momentApi
        app -> commonResources
        app -> zebraMiscApi
        app -> devtoolsApi
        app -> videoCacheApi
        app -> frog
        app -> bizLaunchApi
        app -> galleryApi
        app -> zebraCocosApi
        app -> mvrx
        app -> net
        app -> zebraConfigApi
        app -> zebraRecognizeDumb
        app -> zebraUpgradeApi
        app -> forkMainLib
        app -> bizEvaluateApi
        app -> servCommon
        app -> commonData
        app -> bizPotterApi
        app -> zebraPaymentApi
        app -> errorReportApi
        app -> accountApi
        app -> zebraMediaPlayerApi
        app -> zebraCalculationApi
        app -> zebraMonitorApi
        app -> bizCommon
        app -> liveCommerceWrapperApi
        app -> bizTutorWrapperApi
        app -> zebraui
        app -> zebraFlutterDumb
        app -> kiddoForAppApi
        app -> zebraUploaderApi
        app -> webAppApi
        app -> zebraCocosDumb
        app -> bizCapsuleApi
        app -> commonUi
        app -> log
        app -> zebraDownloaderApi
        app -> bizHomeSupportApi
        app -> storage
        app -> mediaplayerDumb
        app -> zebraShareDumb
        app -> bizTvClassApi
        app -> libCommon
        app -> bizAccountApi
        app -> liveWrapperApi
        app -> zebraShareApi
        app -> debugWindow
        app -> bizFmApi
        app -> appApi
        app -> forkMainResources
        app -> zebraRecognizeApi
        app -> zebraFlutterApi
        app -> webApi
        app -> zebraLottie
        app -> bizPicbookApi
        app -> bizUnitReviewApi
        app -> serverApi
        app -> zebraEyeProtectApi
        app -> zebraDiagnoApi
        app -> zebraCustomerServiceApi
        app -> bizHomeApi
        zebraRecognizeDumb -> libCommon
        zebraRecognizeDumb -> zebraRecognizeApi
        zebraRecognizeDumb -> forkMainLib
        zebraRecognizeDumb -> zebraui
        zebraRecognizeDumb -> commonData
        zebraRecognizeDumb -> zebraLottie
        bizLaunch -> zebraMemoryMonitorApi
        bizLaunch -> zebraRouter
        bizLaunch -> mediaplayerApi
        bizLaunch -> zebraPreDownloaderApi
        bizLaunch -> zebraMqttApi
        bizLaunch -> zebraPrivacyApi
        bizLaunch -> momentApi
        bizLaunch -> commonResources
        bizLaunch -> devtoolsApi
        bizLaunch -> zebraMiscApi
        bizLaunch -> frog
        bizLaunch -> bizLaunchApi
        bizLaunch -> net
        bizLaunch -> zebraCocosApi
        bizLaunch -> zebraConfigApi
        bizLaunch -> zebraCrashCleanApi
        bizLaunch -> zebraUpgradeApi
        bizLaunch -> forkMainLib
        bizLaunch -> commonData
        bizLaunch -> servCommon
        bizLaunch -> bizPotterApi
        bizLaunch -> errorReportApi
        bizLaunch -> accountApi
        bizLaunch -> bizReadingPenApi
        bizLaunch -> zebraMonitorApi
        bizLaunch -> liveCommerceWrapperApi
        bizLaunch -> bizCommon
        bizLaunch -> bizTutorWrapperApi
        bizLaunch -> zebraui
        bizLaunch -> zebraUploaderApi
        bizLaunch -> webAppApi
        bizLaunch -> bizCapsuleApi
        bizLaunch -> log
        bizLaunch -> zebraDownloaderApi
        bizLaunch -> bizHomeSupportApi
        bizLaunch -> storage
        bizLaunch -> bizSplashApi
        bizLaunch -> zebraPushApi
        bizLaunch -> libCommon
        bizLaunch -> bizAccountApi
        bizLaunch -> zebraShareApi
        bizLaunch -> liveWrapperApi
        bizLaunch -> debugWindow
        bizLaunch -> bizFmApi
        bizLaunch -> appApi
        bizLaunch -> forkMainResources
        bizLaunch -> zebraFlutterApi
        bizLaunch -> webApi
        bizLaunch -> bizPicbookApi
        bizLaunch -> serverApi
        bizLaunch -> zebraCustomerServiceApi
        bizLaunch -> bizHomeApi
        bizPotterApi -> libCommon
        bizPotterApi -> libRouter
        bizPotterApi -> commonData
        errorReportApi -> libCommon
        errorReportApi -> libRouter
        errorReportApi -> commonData
        zebraPaymentApi -> libCommon
        zebraPaymentApi -> libRouter
        zebraPaymentApi -> commonData
        mediaplayer -> commonUi
        mediaplayer -> log
        mediaplayer -> mediaplayerApi
        mediaplayer -> forkMainLib
        mediaplayer -> commonData
        mediaplayer -> storage
        mediaplayer -> libCommon
        mediaplayer -> zebraMiscApi
        mediaplayer -> libRouter
        mediaplayer -> zebraui
        mediaplayer -> net
        mediaplayer -> zebraConfigApi
        bizReadingPenApi -> libCommon
        bizReadingPenApi -> libRouter
        bizReadingPenApi -> commonData
        bizCommon -> accountApi
        bizCommon -> libCommon
        bizCommon -> zebraMediaPlayerApi
        bizCommon -> libRouter
        bizCommon -> frog
        bizCommon -> log
        bizCommon -> forkMainLib
        bizCommon -> zebraui
        bizCommon -> commonData
        bizCommon -> servCommon
        bizCommon -> net
        zebraMonitorApi -> libCommon
        zebraMonitorApi -> libRouter
        zebraMonitorApi -> commonData
        bizTutorWrapperApi -> libCommon
        bizTutorWrapperApi -> libRouter
        bizTutorWrapperApi -> commonData
        videoCache -> videoCacheApi
        videoCache -> log
        videoCache -> commonData
        videoCache -> storage
        videoCache -> net
        zebradownloader -> libCommon
        zebradownloader -> log
        zebradownloader -> zebraDownloaderApi
        zebradownloader -> commonData
        zebradownloader -> servCommon
        zebradownloader -> zebraPreDownloaderApi
        zebradownloader -> storage
        zebradownloader -> net
        zebradownloader -> zebraConfigApi
        zebraUploaderApi -> libCommon
        zebraUploaderApi -> libRouter
        zebraUploaderApi -> commonData
        zebraCocosDumb -> commonData
        zebraCrashClean -> libCommon
        zebraCrashClean -> libRouter
        zebraCrashClean -> log
        zebraCrashClean -> commonData
        zebraCrashClean -> storage
        zebraCrashClean -> zebraConfigApi
        zebraCrashClean -> zebraCrashCleanApi
        bizUnitReview -> zebraMediaPlayerDumb
        bizUnitReview -> zebraRouter
        bizUnitReview -> log
        bizUnitReview -> mediaplayerApi
        bizUnitReview -> webAppDumb
        bizUnitReview -> zebraPreDownloaderApi
        bizUnitReview -> zebraDownloaderApi
        bizUnitReview -> storage
        bizUnitReview -> mediaplayerDumb
        bizUnitReview -> libCommon
        bizUnitReview -> bizTvClassApi
        bizUnitReview -> commonResources
        bizUnitReview -> frog
        bizUnitReview -> bizLaunchApi
        bizUnitReview -> net
        bizUnitReview -> zebraConfigApi
        bizUnitReview -> appApi
        bizUnitReview -> forkMainResources
        bizUnitReview -> zebraRecognizeApi
        bizUnitReview -> forkMainLib
        bizUnitReview -> commonData
        bizUnitReview -> servCommon
        bizUnitReview -> bizUnitReviewApi
        bizUnitReview -> serverApi
        bizUnitReview -> accountApi
        bizUnitReview -> zebraMonitorApi
        bizUnitReview -> zebraui
        bizUnitReview -> bizHomeApi
        bizUnitReview -> webAppApi
        log -> debugWindow
        bizHomeSupportApi -> libCommon
        bizHomeSupportApi -> libRouter
        bizHomeSupportApi -> commonData
        liveWrapper -> accountApi
        liveWrapper -> libCommon
        liveWrapper -> zebraRouter
        liveWrapper -> frog
        liveWrapper -> log
        liveWrapper -> commonData
        liveWrapper -> liveWrapperApi
        liveWrapper -> net
        liveWrapper -> zebraConfigApi
        moment -> zebraMediaPlayerDumb
        moment -> zebraRouter
        moment -> commonUi
        moment -> forkMainResources
        moment -> zebraRecognizeApi
        moment -> mediaplayerApi
        moment -> forkMainLib
        moment -> zebraDownloaderApi
        moment -> curryPushApi
        moment -> momentcommon
        moment -> zebraPushApi
        moment -> accountApi
        moment -> libCommon
        moment -> commonResources
        moment -> zebraMediaPlayerApi
        moment -> zebraui
        moment -> zebraShareApi
        moment -> mvrx
        moment -> zebraUploaderApi
        moment -> zebraConfigApi
        moment -> webAppApi
        zebraPushApi -> libCommon
        zebraPushApi -> libRouter
        zebraPushApi -> commonData
        bizTvClassApi -> libCommon
        bizTvClassApi -> libRouter
        bizTvClassApi -> commonData
        bizReadingPen -> zebraRouter
        bizReadingPen -> log
        bizReadingPen -> forkMainLib
        bizReadingPen -> commonData
        bizReadingPen -> storage
        bizReadingPen -> accountApi
        bizReadingPen -> libCommon
        bizReadingPen -> bizReadingPenApi
        bizReadingPen -> frog
        bizReadingPen -> zebraui
        bizReadingPen -> net
        bizReadingPen -> appApi
        web -> libCommon
        web -> zebraRouter
        web -> log
        web -> forkMainLib
        web -> zebraui
        web -> commonData
        web -> galleryApi
        web -> zebraShareApi
        web -> storage
        web -> webApi
        web -> net
        liveWrapperApi -> libCommon
        liveWrapperApi -> libRouter
        liveWrapperApi -> commonData
        devtools -> bizCapsuleApi
        devtools -> zebraRouter
        devtools -> mediaplayerApi
        devtools -> log
        devtools -> storage
        devtools -> bizAiTalkApi
        devtools -> mediaplayerDumb
        devtools -> momentApi
        devtools -> libCommon
        devtools -> commonResources
        devtools -> bizAccountApi
        devtools -> devtoolsApi
        devtools -> frog
        devtools -> net
        devtools -> debugWindow
        devtools -> appApi
        devtools -> zebraConfigApi
        devtools -> forkMainResources
        devtools -> forkMainLib
        devtools -> commonData
        devtools -> bizPotterApi
        devtools -> accountApi
        devtools -> liveCommerceWrapperApi
        devtools -> zebraui
        bizFmApi -> libCommon
        bizFmApi -> libRouter
        bizFmApi -> commonData
        debugWindow -> commonResources
        debugWindow -> forkMainResources
        zebraUploader -> accountApi
        zebraUploader -> libCommon
        zebraUploader -> libRouter
        zebraUploader -> zebraMiscApi
        zebraUploader -> frog
        zebraUploader -> log
        zebraUploader -> commonData
        zebraUploader -> net
        zebraUploader -> zebraConfigApi
        zebraUploader -> zebraUploaderApi
        zebraCustomerService -> zebraRouter
        zebraCustomerService -> log
        zebraCustomerService -> forkMainLib
        zebraCustomerService -> commonData
        zebraCustomerService -> servCommon
        zebraCustomerService -> accountApi
        zebraCustomerService -> libCommon
        zebraCustomerService -> bizAccountApi
        zebraCustomerService -> zebraCustomerServiceApi
        zebraCustomerService -> zebraui
        zebraCustomerService -> net
        zebraCustomerService -> mvrx
        zebraCustomerService -> zebraConfigApi
        zebraCustomerService -> webAppApi
        zebraRecognizeApi -> libCommon
        zebraRecognizeApi -> libRouter
        zebraRecognizeApi -> commonData
        bizUnitReviewApi -> libCommon
        bizUnitReviewApi -> libRouter
        bizUnitReviewApi -> commonData
        zebraEyeProtectApi -> libCommon
        zebraEyeProtectApi -> libRouter
        zebraEyeProtectApi -> commonData
        zebraDiagnoApi -> libCommon
        zebraDiagnoApi -> libRouter
        zebraDiagnoApi -> commonData
        zebraCustomerServiceApi -> libCommon
        zebraCustomerServiceApi -> libRouter
        zebraCustomerServiceApi -> commonData
        zebraShare -> log
        zebraShare -> forkMainLib
        zebraShare -> commonData
        zebraShare -> servCommon
        zebraShare -> zebraDownloaderApi
        zebraShare -> storage
        zebraShare -> accountApi
        zebraShare -> libCommon
        zebraShare -> libRouter
        zebraShare -> frog
        zebraShare -> zebraui
        zebraShare -> zebraShareApi
        zebraShare -> net
        zebraShare -> zebraUploaderApi
        zebraShare -> zebraConfigApi
        zebraShare -> appApi
        zebraDownloaderDumb -> libRouter
        zebraDownloaderDumb -> commonData
        zebraDownloaderDumb -> zebraDownloaderApi
        bizHomeHD -> zebraRouter
        bizHomeHD -> log
        bizHomeHD -> zebraDownloaderApi
        bizHomeHD -> zebraPreDownloaderApi
        bizHomeHD -> bizHomeSupportApi
        bizHomeHD -> storage
        bizHomeHD -> bizHomeHDApi
        bizHomeHD -> zebraPrivacyApi
        bizHomeHD -> zebraPushApi
        bizHomeHD -> momentApi
        bizHomeHD -> libCommon
        bizHomeHD -> bizTvClassApi
        bizHomeHD -> commonResources
        bizHomeHD -> bizAccountApi
        bizHomeHD -> zebraMiscApi
        bizHomeHD -> frog
        bizHomeHD -> bizLaunchApi
        bizHomeHD -> net
        bizHomeHD -> zebraConfigApi
        bizHomeHD -> appApi
        bizHomeHD -> zebraCrashCleanApi
        bizHomeHD -> zebraUpgradeApi
        bizHomeHD -> forkMainResources
        bizHomeHD -> forkMainLib
        bizHomeHD -> servCommon
        bizHomeHD -> commonData
        bizHomeHD -> bizPotterApi
        bizHomeHD -> errorReportApi
        bizHomeHD -> zebraPaymentApi
        bizHomeHD -> zebraLottie
        bizHomeHD -> serverApi
        bizHomeHD -> accountApi
        bizHomeHD -> zebraMediaPlayerApi
        bizHomeHD -> bizMessageBoxApi
        bizHomeHD -> bizCommon
        bizHomeHD -> zebraui
        bizHomeHD -> bizHome
        bizHomeHD -> webAppApi
        bizHomeHD -> bizHomeApi
        webapp -> zebraRouter
        webapp -> log
        webapp -> zebraPreDownloaderApi
        webapp -> bizHomeSupportApi
        webapp -> storage
        webapp -> momentApi
        webapp -> libCommon
        webapp -> bizAccountApi
        webapp -> frog
        webapp -> bizLaunchApi
        webapp -> galleryApi
        webapp -> zebraShareApi
        webapp -> net
        webapp -> mvrx
        webapp -> zebraConfigApi
        webapp -> appApi
        webapp -> zebraRecognizeApi
        webapp -> forkMainLib
        webapp -> commonData
        webapp -> servCommon
        webapp -> bizPotterApi
        webapp -> webApi
        webapp -> zebraPaymentApi
        webapp -> serverApi
        webapp -> accountApi
        webapp -> zebraCustomerServiceApi
        webapp -> zebraMonitorApi
        webapp -> zebraui
        webapp -> zebraShare
        webapp -> kiddoForAppApi
        webapp -> zebraUploaderApi
        webapp -> bizHomeApi
        webapp -> webAppApi
        zebraMediaPlayerDumb -> log
        zebraMediaPlayerDumb -> mediaplayerApi
        zebraMediaPlayerDumb -> forkMainLib
        zebraMediaPlayerDumb -> commonData
        zebraMediaPlayerDumb -> zebraDownloaderApi
        zebraMediaPlayerDumb -> storage
        zebraMediaPlayerDumb -> bizPicbookApi
        zebraMediaPlayerDumb -> mediaplayerDumb
        zebraMediaPlayerDumb -> zebraEyeProtectApi
        zebraMediaPlayerDumb -> accountApi
        zebraMediaPlayerDumb -> libCommon
        zebraMediaPlayerDumb -> zebraMediaPlayerApi
        zebraMediaPlayerDumb -> libRouter
        zebraMediaPlayerDumb -> frog
        zebraMediaPlayerDumb -> zebraMonitorApi
        zebraMediaPlayerDumb -> zebraui
        zebraMediaPlayerDumb -> net
        zebraMediaPlayerDumb -> zebraUploaderApi
        bizPotter -> log
        bizPotter -> webAppDumb
        bizPotter -> commonData
        bizPotter -> bizPotterApi
        bizPotter -> servCommon
        bizPotter -> bizHomeSupportApi
        bizPotter -> storage
        bizPotter -> bizHomeHDApi
        bizPotter -> serverApi
        bizPotter -> accountApi
        bizPotter -> libCommon
        bizPotter -> bizMessageBoxApi
        bizPotter -> bizAccountApi
        bizPotter -> libRouter
        bizPotter -> net
        bizPotter -> appApi
        bizPotter -> bizFmApi
        bizPotter -> webAppApi
        bizPotter -> bizHomeApi
        zebraFlutter -> accountApi
        zebraFlutter -> libCommon
        zebraFlutter -> zebraRouter
        zebraFlutter -> libRouter
        zebraFlutter -> log
        zebraFlutter -> commonData
        zebraFlutter -> zebraFlutterApi
        zebraFlutter -> storage
        zebraFlutter -> net
        zebraFlutter -> zebraConfigApi
        bizCapsuleToy -> bizCapsuleApi
        bizCapsuleToy -> zebraRouter
        bizCapsuleToy -> forkMainResources
        bizCapsuleToy -> log
        bizCapsuleToy -> mediaplayerApi
        bizCapsuleToy -> forkMainLib
        bizCapsuleToy -> commonData
        bizCapsuleToy -> zebraPreDownloaderApi
        bizCapsuleToy -> storage
        bizCapsuleToy -> zebraLottie
        bizCapsuleToy -> mediaplayerDumb
        bizCapsuleToy -> accountApi
        bizCapsuleToy -> zebraShareDumb
        bizCapsuleToy -> libCommon
        bizCapsuleToy -> commonResources
        bizCapsuleToy -> frog
        bizCapsuleToy -> zebraui
        bizCapsuleToy -> zebraShareApi
        bizCapsuleToy -> net
        bizCapsuleToy -> zebraConfigApi
        bizCapsuleToy -> appApi
        bizCapsuleToy -> webAppApi
        mediaplayerApi -> libCommon
        mediaplayerApi -> libRouter
        mediaplayerApi -> commonData
        webAppDumb -> libCommon
        webAppDumb -> libRouter
        webAppDumb -> forkMainLib
        webAppDumb -> zebraui
        webAppDumb -> commonData
        webAppDumb -> zebraShareApi
        webAppDumb -> webApi
        webAppDumb -> webAppApi
        bizBaseSubject -> bizCapsuleApi
        bizBaseSubject -> zebraMediaPlayerDumb
        bizBaseSubject -> zebraRouter
        bizBaseSubject -> mediaplayerApi
        bizBaseSubject -> log
        bizBaseSubject -> zebraDownloaderApi
        bizBaseSubject -> zebraPreDownloaderApi
        bizBaseSubject -> storage
        bizBaseSubject -> mediaplayerDumb
        bizBaseSubject -> libCommon
        bizBaseSubject -> commonResources
        bizBaseSubject -> videoCacheApi
        bizBaseSubject -> frog
        bizBaseSubject -> bizBaseSubjectApi
        bizBaseSubject -> zebraShareApi
        bizBaseSubject -> net
        bizBaseSubject -> zebraCocosApi
        bizBaseSubject -> appApi
        bizBaseSubject -> zebraConfigApi
        bizBaseSubject -> forkMainResources
        bizBaseSubject -> zebraRecognizeApi
        bizBaseSubject -> forkMainLib
        bizBaseSubject -> commonData
        bizBaseSubject -> bizEvaluateApi
        bizBaseSubject -> servCommon
        bizBaseSubject -> errorReportApi
        bizBaseSubject -> serverApi
        bizBaseSubject -> zebraEyeProtectApi
        bizBaseSubject -> accountApi
        bizBaseSubject -> zebraMediaPlayerApi
        bizBaseSubject -> zebraMonitorApi
        bizBaseSubject -> zebraui
        bizBaseSubject -> bizHomeApi
        zebraMisc -> accountApi
        zebraMisc -> libCommon
        zebraMisc -> libRouter
        zebraMisc -> zebraMiscApi
        zebraMisc -> log
        zebraMisc -> commonData
        zebraMisc -> net
        zebraMisc -> serverApi
        zebraMisc -> zebraConfigApi
        liveCommerceWrapper -> conan-live-commerce-android
        liveCommerceWrapper -> libCommon
        liveCommerceWrapper -> bizAccountApi
        liveCommerceWrapper -> zebraRouter
        liveCommerceWrapper -> liveCommerceWrapperApi
        liveCommerceWrapper -> webAppDumb
        liveCommerceWrapper -> commonData
        liveCommerceWrapper -> webApi
        liveCommerceWrapper -> webAppApi
        momentcommon -> forkMainResources
        momentcommon -> zebraRouter
        momentcommon -> log
        momentcommon -> forkMainLib
        momentcommon -> commonData
        momentcommon -> storage
        momentcommon -> zebraPrivacyApi
        momentcommon -> momentApi
        momentcommon -> accountApi
        momentcommon -> libCommon
        momentcommon -> commonResources
        momentcommon -> frog
        momentcommon -> zebraui
        momentcommon -> zebraShareApi
        momentcommon -> net
        momentcommon -> zebraConfigApi
        momentApi -> libCommon
        momentApi -> libRouter
        momentApi -> commonData
        videoCacheApi -> libCommon
        videoCacheApi -> libRouter
        videoCacheApi -> commonData
        bizLaunchApi -> libCommon
        bizLaunchApi -> libRouter
        bizLaunchApi -> commonData
        net -> libCommon
        net -> log
        net -> commonData
        net -> legacyApiCall
        mvrx -> commonResources
        mvrx -> forkMainResources
        zebraConfigApi -> libCommon
        zebraConfigApi -> libRouter
        zebraConfigApi -> commonData
        zebraConfigApi -> legacyApiCall
        zebraCrashCleanApi -> libCommon
        zebraCrashCleanApi -> libRouter
        zebraCrashCleanApi -> commonData
        zebraUpgradeApi -> libCommon
        zebraUpgradeApi -> libRouter
        zebraUpgradeApi -> commonData
        zebraMediaPlayer -> zebraRouter
        zebraMediaPlayer -> mediaplayerApi
        zebraMediaPlayer -> log
        zebraMediaPlayer -> zebraDownloaderApi
        zebraMediaPlayer -> storage
        zebraMediaPlayer -> mediaplayerDumb
        zebraMediaPlayer -> libCommon
        zebraMediaPlayer -> zebraMiscApi
        zebraMediaPlayer -> frog
        zebraMediaPlayer -> net
        zebraMediaPlayer -> zebraConfigApi
        zebraMediaPlayer -> appApi
        zebraMediaPlayer -> forkMainLib
        zebraMediaPlayer -> commonData
        zebraMediaPlayer -> errorReportApi
        zebraMediaPlayer -> bizPicbookApi
        zebraMediaPlayer -> zebraEyeProtectApi
        zebraMediaPlayer -> accountApi
        zebraMediaPlayer -> zebraDiagnoApi
        zebraMediaPlayer -> zebraMediaPlayerApi
        zebraMediaPlayer -> libRouter
        zebraMediaPlayer -> zebraMonitorApi
        zebraMediaPlayer -> zebraui
        zebraMediaPlayer -> zebraUploaderApi
        bizEvaluateApi -> libCommon
        bizEvaluateApi -> libRouter
        bizEvaluateApi -> commonData
        commonData -> libCommon
        commonData -> commonResources
        commonData -> forkMainResources
        commonData -> log
        commonData -> legacyApiCall
        servCommon -> libCommon
        servCommon -> commonResources
        servCommon -> libRouter
        servCommon -> commonUi
        servCommon -> forkMainResources
        servCommon -> frog
        servCommon -> log
        servCommon -> commonData
        bizFm -> zebraRouter
        bizFm -> log
        bizFm -> forkMainLib
        bizFm -> commonData
        bizFm -> storage
        bizFm -> accountApi
        bizFm -> zebraShareDumb
        bizFm -> libCommon
        bizFm -> zebraMediaPlayerApi
        bizFm -> frog
        bizFm -> zebraMonitorApi
        bizFm -> zebraui
        bizFm -> zebraShareApi
        bizFm -> net
        bizFm -> mvrx
        bizFm -> bizFmApi
        bizFm -> appApi
        bizFm -> zebraConfigApi
        accountApi -> libCommon
        accountApi -> libRouter
        accountApi -> commonData
        zebraMediaPlayerApi -> libCommon
        zebraMediaPlayerApi -> libRouter
        zebraMediaPlayerApi -> commonData
        libRouter -> libCommon
        libRouter -> commonData
        zebraCalculationApi -> libCommon
        zebraCalculationApi -> libRouter
        zebraCalculationApi -> commonData
        liveCommerceWrapperApi -> libCommon
        liveCommerceWrapperApi -> libRouter
        liveCommerceWrapperApi -> commonData
        zebraCalculation -> zebraRouter
        zebraCalculation -> forkMainResources
        zebraCalculation -> log
        zebraCalculation -> mediaplayerApi
        zebraCalculation -> forkMainLib
        zebraCalculation -> commonData
        zebraCalculation -> zebraDownloaderApi
        zebraCalculation -> storage
        zebraCalculation -> zebraLottie
        zebraCalculation -> mediaplayerDumb
        zebraCalculation -> accountApi
        zebraCalculation -> zebraShareDumb
        zebraCalculation -> libCommon
        zebraCalculation -> commonResources
        zebraCalculation -> zebraCalculationApi
        zebraCalculation -> frog
        zebraCalculation -> zebraMonitorApi
        zebraCalculation -> zebraui
        zebraCalculation -> zebraShareApi
        zebraCalculation -> net
        zebraCalculation -> appApi
        zebraui -> libCommon
        zebraui -> commonResources
        zebraui -> commonUi
        zebraui -> forkMainResources
        zebraui -> frog
        zebraui -> log
        zebraui -> commonData
        zebraui -> storage
        zebraui -> zebraLottie
        zebraFlutterDumb -> commonData
        zebraFlutterDumb -> zebraFlutterApi
        zebraConfig -> libCommon
        zebraConfig -> zebraRouter
        zebraConfig -> log
        zebraConfig -> commonData
        zebraConfig -> net
        zebraConfig -> zebraConfigApi
        zebraDiagno -> accountApi
        zebraDiagno -> libCommon
        zebraDiagno -> zebraDiagnoApi
        zebraDiagno -> libRouter
        zebraDiagno -> log
        zebraDiagno -> commonData
        zebraDiagno -> storage
        zebraDiagno -> zebraConfigApi
        bizMessageBox -> accountApi
        bizMessageBox -> libCommon
        bizMessageBox -> bizMessageBoxApi
        bizMessageBox -> zebraRouter
        bizMessageBox -> frog
        bizMessageBox -> log
        bizMessageBox -> forkMainLib
        bizMessageBox -> zebraui
        bizMessageBox -> commonData
        bizMessageBox -> net
        bizHome -> zebraRouter
        bizHome -> mediaplayerApi
        bizHome -> zebraMqttApi
        bizHome -> zebraPreDownloaderApi
        bizHome -> zebraPrivacyApi
        bizHome -> momentApi
        bizHome -> commonResources
        bizHome -> zebraMiscApi
        bizHome -> frog
        bizHome -> bizLaunchApi
        bizHome -> net
        bizHome -> mvrx
        bizHome -> zebraConfigApi
        bizHome -> zebraCrashCleanApi
        bizHome -> zebraUpgradeApi
        bizHome -> forkMainLib
        bizHome -> commonData
        bizHome -> servCommon
        bizHome -> zebraPaymentApi
        bizHome -> errorReportApi
        bizHome -> accountApi
        bizHome -> bizReadingPenApi
        bizHome -> zebraMediaPlayerApi
        bizHome -> zebraMonitorApi
        bizHome -> liveCommerceWrapperApi
        bizHome -> bizCommon
        bizHome -> zebraui
        bizHome -> zebraUploaderApi
        bizHome -> webAppApi
        bizHome -> bizCapsuleApi
        bizHome -> log
        bizHome -> zebraDownloaderApi
        bizHome -> bizHomeSupportApi
        bizHome -> storage
        bizHome -> bizSplashApi
        bizHome -> mediaplayerDumb
        bizHome -> zebraPushApi
        bizHome -> bizTvClassApi
        bizHome -> libCommon
        bizHome -> bizAccountApi
        bizHome -> zebraShareApi
        bizHome -> appApi
        bizHome -> bizFmApi
        bizHome -> forkMainResources
        bizHome -> zebraLottie
        bizHome -> bizUnitReviewApi
        bizHome -> bizPicbookApi
        bizHome -> serverApi
        bizHome -> bizMessageBoxApi
        bizHome -> zebraCustomerServiceApi
        bizHome -> bizHomeApi
        webAppApi -> libCommon
        webAppApi -> libRouter
        webAppApi -> commonData
        webAppApi -> zebraShareApi
        bizHomeSupport -> bizCapsuleApi
        bizHomeSupport -> zebraRouter
        bizHomeSupport -> log
        bizHomeSupport -> mediaplayerApi
        bizHomeSupport -> zebraDownloaderApi
        bizHomeSupport -> zebraPreDownloaderApi
        bizHomeSupport -> bizHomeSupportApi
        bizHomeSupport -> storage
        bizHomeSupport -> zebraPrivacyApi
        bizHomeSupport -> momentApi
        bizHomeSupport -> libCommon
        bizHomeSupport -> bizAccountApi
        bizHomeSupport -> frog
        bizHomeSupport -> bizLaunchApi
        bizHomeSupport -> zebraShareApi
        bizHomeSupport -> galleryApi
        bizHomeSupport -> liveWrapperApi
        bizHomeSupport -> net
        bizHomeSupport -> mvrx
        bizHomeSupport -> zebraCocosApi
        bizHomeSupport -> zebraConfigApi
        bizHomeSupport -> appApi
        bizHomeSupport -> bizFmApi
        bizHomeSupport -> zebraUpgradeApi
        bizHomeSupport -> bizPoetryReciteApi
        bizHomeSupport -> forkMainLib
        bizHomeSupport -> commonData
        bizHomeSupport -> zebraFlutterApi
        bizHomeSupport -> bizPotterApi
        bizHomeSupport -> bizPicbookApi
        bizHomeSupport -> serverApi
        bizHomeSupport -> zebraEyeProtectApi
        bizHomeSupport -> accountApi
        bizHomeSupport -> zebraDiagnoApi
        bizHomeSupport -> bizReadingPenApi
        bizHomeSupport -> zebraMediaPlayerApi
        bizHomeSupport -> zebraui
        bizHomeSupport -> zebraUploaderApi
        bizHomeSupport -> webAppApi
        bizCapsuleApi -> libCommon
        bizCapsuleApi -> libRouter
        bizCapsuleApi -> commonData
        zebraEyeProtect -> zebraEyeProtectApi
        zebraEyeProtect -> libCommon
        zebraEyeProtect -> commonResources
        zebraEyeProtect -> zebraRouter
        zebraEyeProtect -> forkMainResources
        zebraEyeProtect -> frog
        zebraEyeProtect -> log
        zebraEyeProtect -> forkMainLib
        zebraEyeProtect -> zebraui
        zebraEyeProtect -> commonData
        zebraEyeProtect -> zebraConfigApi
        zebraMonitor -> libCommon
        zebraMonitor -> libRouter
        zebraMonitor -> zebraMonitorApi
        zebraMonitor -> frog
        zebraMonitor -> log
        zebraMonitor -> commonData
        zebraMonitor -> zebraConfigApi
        commonUi -> libCommon
        commonUi -> commonData
        bizAiTalk -> zebraRouter
        bizAiTalk -> zebraRecognizeApi
        bizAiTalk -> log
        bizAiTalk -> forkMainLib
        bizAiTalk -> commonData
        bizAiTalk -> storage
        bizAiTalk -> bizAiTalkApi
        bizAiTalk -> accountApi
        bizAiTalk -> libCommon
        bizAiTalk -> zebraMediaPlayerApi
        bizAiTalk -> frog
        bizAiTalk -> zebraui
        bizAiTalk -> net
        bizAiTalk -> appApi
        bizAiTalk -> webAppApi
        zebraDownloaderApi -> libCommon
        zebraDownloaderApi -> libRouter
        zebraDownloaderApi -> commonData
        momentplay -> zebraRouter
        momentplay -> mediaplayerApi
        momentplay -> forkMainLib
        momentplay -> zebraDownloaderApi
        momentplay -> servCommon
        momentplay -> curryPushApi
        momentplay -> momentcommon
        momentplay -> zebraPushApi
        momentplay -> accountApi
        momentplay -> libCommon
        momentplay -> videoCacheApi
        momentplay -> zebraui
        momentplay -> zebraShareApi
        momentplay -> zebraConfigApi
        momentplay -> webAppApi
        bizTvClass -> zebraMediaPlayerDumb
        bizTvClass -> zebraRouter
        bizTvClass -> log
        bizTvClass -> mediaplayerApi
        bizTvClass -> webAppDumb
        bizTvClass -> zebraDownloaderApi
        bizTvClass -> zebraPreDownloaderApi
        bizTvClass -> storage
        bizTvClass -> mediaplayerDumb
        bizTvClass -> bizTvClassApi
        bizTvClass -> libCommon
        bizTvClass -> commonResources
        bizTvClass -> bizAccountApi
        bizTvClass -> frog
        bizTvClass -> bizLaunchApi
        bizTvClass -> zebraShareApi
        bizTvClass -> liveWrapperApi
        bizTvClass -> net
        bizTvClass -> zebraCocosApi
        bizTvClass -> zebraConfigApi
        bizTvClass -> appApi
        bizTvClass -> zebraRecognizeDumb
        bizTvClass -> forkMainResources
        bizTvClass -> zebraRecognizeApi
        bizTvClass -> forkMainLib
        bizTvClass -> commonData
        bizTvClass -> servCommon
        bizTvClass -> zebraLottie
        bizTvClass -> serverApi
        bizTvClass -> accountApi
        bizTvClass -> zebraMediaPlayerApi
        bizTvClass -> zebraMonitorApi
        bizTvClass -> bizCommon
        bizTvClass -> zebraui
        bizTvClass -> zebraUploaderApi
        bizTvClass -> bizHomeApi
        bizTvClass -> webAppApi
        bizTvClass -> zebraCocosDumb
        storage -> libCommon
        storage -> frog
        storage -> log
        storage -> commonData
        storage -> net
        bizSplashApi -> libCommon
        bizSplashApi -> libRouter
        bizSplashApi -> commonData
        mediaplayerDumb -> libCommon
        mediaplayerDumb -> commonUi
        mediaplayerDumb -> zebraMiscApi
        mediaplayerDumb -> libRouter
        mediaplayerDumb -> log
        mediaplayerDumb -> mediaplayerApi
        mediaplayerDumb -> forkMainLib
        mediaplayerDumb -> zebraui
        mediaplayerDumb -> commonData
        mediaplayerDumb -> storage
        mediaplayerDumb -> net
        conan-live-commerce-android -> libCommon
        conan-live-commerce-android -> zebraRouter
        conan-live-commerce-android -> forkMainLib
        conan-live-commerce-android -> zebraui
        conan-live-commerce-android -> webAppDumb
        conan-live-commerce-android -> commonData
        conan-live-commerce-android -> mvrx
        conan-live-commerce-android -> appApi
        conan-live-commerce-android -> webAppApi
        zebraMqtt -> zebraRouter
        zebraMqtt -> log
        zebraMqtt -> forkMainLib
        zebraMqtt -> commonData
        zebraMqtt -> zebraMqttApi
        zebraMqtt -> bizHomeSupportApi
        zebraMqtt -> storage
        zebraMqtt -> serverApi
        zebraMqtt -> accountApi
        zebraMqtt -> libCommon
        zebraMqtt -> frog
        zebraMqtt -> zebraui
        zebraMqtt -> bizLaunchApi
        zebraMqtt -> net
        zebraMqtt -> zebraConfigApi
        zebraMqtt -> appApi
        zebraMqtt -> webAppApi
        zebraShareDumb -> libCommon
        zebraShareDumb -> commonData
        zebraShareDumb -> zebraShareApi
        libCommon -> commonResources
        libCommon -> forkMainResources
        libCommon -> frog
        libCommon -> log
        libCommon -> mvrx
        bizAccountApi -> libCommon
        bizAccountApi -> libRouter
        bizAccountApi -> commonData
        zebraShareApi -> libCommon
        zebraShareApi -> libRouter
        zebraShareApi -> commonData
        zebraShareApi -> legacyApiCall
        zebraPush -> zebraPushApi
        zebraPush -> momentApi
        zebraPush -> libCommon
        zebraPush -> zebraRouter
        zebraPush -> frog
        zebraPush -> log
        zebraPush -> forkMainLib
        zebraPush -> zebraui
        zebraPush -> commonData
        zebraPush -> net
        zebraPush -> zebraPrivacyApi
        appApi -> libCommon
        appApi -> libRouter
        appApi -> commonData
        bizPicbook -> zebraRouter
        bizPicbook -> log
        bizPicbook -> zebraPreDownloaderApi
        bizPicbook -> storage
        bizPicbook -> libCommon
        bizPicbook -> bizAccountApi
        bizPicbook -> commonResources
        bizPicbook -> frog
        bizPicbook -> bizBaseSubjectApi
        bizPicbook -> zebraShareApi
        bizPicbook -> mvrx
        bizPicbook -> net
        bizPicbook -> bizFmApi
        bizPicbook -> appApi
        bizPicbook -> forkMainResources
        bizPicbook -> zebraRecognizeApi
        bizPicbook -> forkMainLib
        bizPicbook -> commonData
        bizPicbook -> servCommon
        bizPicbook -> zebraFlutterApi
        bizPicbook -> zebraLottie
        bizPicbook -> bizPicbookApi
        bizPicbook -> accountApi
        bizPicbook -> zebraMediaPlayerApi
        bizPicbook -> bizCommon
        bizPicbook -> zebraui
        bizPicbook -> zebraUploaderApi
        bizPoetryReciteApi -> libCommon
        bizPoetryReciteApi -> libRouter
        bizPoetryReciteApi -> commonData
        zebraFlutterApi -> libCommon
        zebraFlutterApi -> libRouter
        zebraFlutterApi -> commonData
        zebraPrivacy -> libCommon
        zebraPrivacy -> zebraRouter
        zebraPrivacy -> frog
        zebraPrivacy -> log
        zebraPrivacy -> forkMainLib
        zebraPrivacy -> zebraui
        zebraPrivacy -> bizLaunchApi
        zebraPrivacy -> commonData
        zebraPrivacy -> zebraPrivacyApi
        webApi -> libCommon
        webApi -> libRouter
        webApi -> commonData
        bizPicbookApi -> libCommon
        bizPicbookApi -> libRouter
        bizPicbookApi -> commonData
        serverApi -> momentApi
        serverApi -> libCommon
        serverApi -> log
        serverApi -> commonData
        serverApi -> net
        bizTutorWrapper -> accountApi
        bizTutorWrapper -> libCommon
        bizTutorWrapper -> libRouter
        bizTutorWrapper -> bizTutorWrapperApi
        bizTutorWrapper -> commonData
        bizTutorWrapper -> bizLaunchApi
        bizTutorWrapper -> net
        bizTutorWrapper -> zebraPrivacyApi
        bizMessageBoxApi -> libCommon
        bizMessageBoxApi -> libRouter
        bizMessageBoxApi -> commonData
        account -> zebraRouter
        account -> log
        account -> zebraMqttApi
        account -> bizHomeSupportApi
        account -> zebraPushApi
        account -> momentApi
        account -> libCommon
        account -> bizAccountApi
        account -> zebraMiscApi
        account -> frog
        account -> bizLaunchApi
        account -> liveWrapperApi
        account -> net
        account -> zebraConfigApi
        account -> bizFmApi
        account -> appApi
        account -> forkMainLib
        account -> commonData
        account -> servCommon
        account -> bizPotterApi
        account -> curryPushApi
        account -> webApi
        account -> bizPicbookApi
        account -> serverApi
        account -> accountApi
        account -> bizReadingPenApi
        account -> zebraCustomerServiceApi
        account -> zebraui
        account -> bizHomeApi
        bizHomeApi -> libCommon
        bizHomeApi -> libRouter
        bizHomeApi -> commonData
    """.trimIndent()
}